### ISSUE TITLE
[Demand] Input & Display length limitation for Persona name & Wallet name

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#1130]
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | Figma_Link_Here____
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Introduction

There should length limits.

Type | Limit
--- | ---
Persona | 32 characters
Wallet | 32 characters

## Notes

- "Vladimir Joseph de la Fayette" is 29-char long. 32 should be enough.

**Comment by Tedko** [comment]
<img width="1444" alt="Screen Shot 2020-10-17 at 02 11 32" src="https://user-images.githubusercontent.com/6687437/96293899-173eff80-101e-11eb-977b-92a75a79032b.png">


Will need a quick fix otherwise no way to ues ```...``` of the wallet

(normal case below)

<img width="1444" alt="Screen Shot 2020-10-17 at 02 12 14" src="https://user-images.githubusercontent.com/6687437/96293969-33db3780-101e-11eb-96a1-fae87ec3fe53.png">


assigned to @zhouhanseng

**Comment by Tedko** [comment]
Also may require a display area length limit (32  char; for anything longer than that do ```you name abcd ....```) in case some one just break it through change the name at the Database json level.
