### ISSUE TITLE
Just script: use of  'shell: true'

### ISSUE THREAD

**Issue by Misaka-0x447f** [DimensionDev/Maskbook#150]
> without this things won't work but it said this option is dangerous.
-- @Artoria2e5

**Comment by Artoria2e5** [comment]
It's a long story.

#134 is built on a strange basis with `shell: true` but a list-based thing. @SunriseFox SQUASHED it so it looks like I added it, but do a [blame](https://github.com/DimensionDev/Maskbook/blame/8f53c2640375e27afbb94a36dbb5a1fc78735fa8/just.config.js) on the original PR and you will see it came from a much more earlier state at cc574928dcf64af1f3b2f23018e0e03d37d0cc54. An inappropriate merge at some point thus reverted the removal of `shell: true` in 4cfa4d175c1c238e24144fe104a1f74ac837b7bd. @Jack-Works further rebased the squashed commit into master and added the comment, probably because he thought it was intentional.

Moral of the story? Don't squash things if you don't want to put words into other people's mouths.

**Comment by Misaka-0x447f** [comment]
For now, squash merge button has been removed.

**Comment by Artoria2e5** [comment]
And guess what? Not using `shell: true` actually causes it to fail. If you do `ls node_modules/.bin`, you will see a bunch of commands with and without the `.cmd` suffix. The ones without the suffix are usual Unix shell scripts that are useless anyway, and the ones with `.cmd` are what we actually use on windows.

Now the thing is `.cmd` files are only recognized as a "command" when `shell: true` is used. The system's native spawning/exec-ing mechanism does not do the same. See https://nodejs.org/api/child_process.html#child_process_spawning_bat_and_cmd_files_on_windows.

I don't think this can be fixed at all. We should probably accept it as a fact of life.

**Comment by Misaka-0x447f** [comment]
Speedy close requested.
