### ISSUE TITLE
[Bug] ETH icon display error in Mask wallet

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#1917]
<img width="1611" alt="Screen Shot 2020-11-17 at 14 18 42" src="https://user-images.githubusercontent.com/6687437/99354160-dec26800-28e0-11eb-93c2-caaab13f2c7b.png">

**Comment by zhouhanseng** [comment]
@Tedko This bug is caused by bad network so that image download failed which leads to use the default icon. The current default icon does not make sense, we should load local ETH fallback icon when network request failed. 

But it is impossible to give fallback for [all assets](https://github.com/trustwallet/assets/tree/master/blockchains/ethereum/assets), so please provide an address of common-used assets list.
