### ISSUE TITLE
[Task] Integrated stego-js@2 

### ISSUE THREAD

**Issue by septs** [DimensionDev/Maskbook#2116]
## Introduction and Background

/_Describe the background of this task_/

## Content

1. [ ] Inject image payload version control into text payload (CC @Jack-Works)
2. [ ] Integrated stego-js@2

Effect issues: #1107 #1752 #1956

**Comment by Jack-Works** [comment]
I have talked with @septs. It seems like we need to add a new "hint" in the text message to indicate that the image is a V2 image. The current metadata is not applicable to this case because we need to get the hint _before_ the decryption.

The plan is to add some extra text in the text message (that user must not remove) to hint that this is a V2 image payload, but I don't know if that is OK because users might think "Oh I have chosen the image payload, why I still get some 'encrypted text' in the message?".

**Comment by Jack-Works** [comment]
Oh, wait there is some egenomics problem. If the auto image paste failed the user needs to add the text part also to let the decryption successfully.

**Comment by Tedko** [comment]
@septs @Jack-Works any update?

**Comment by septs** [comment]
known issues:
1. typeson transfer blob to worker very slower (~ 30+ s)
2. image decode failed

**Comment by Jack-Works** [comment]
> typeson transfer blob to worker very slow (30s ~ 1 min)

For this problem, please try my PR #2295 it might resolve the problem
