### ISSUE TITLE
[Bug] DODO link in the exchange tab is wrongly parsed

### ISSUE THREAD

**Issue by yisiliu** [DimensionDev/Maskbook#2634]
### System

- [x] Windows
- [x] Mac OS X
- [x] Linux

### Platform/Browser

- [x] Chrome
- [x] Firefox
- [x] Android
- [x] iOS

### Build Variant

- Where do you get Mask?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

## Bug Info
The Dodo link returned by CMC under the exchange tab in our trader view is wrongly parsed. 
e.g. 
USDT/USDC -> https://app.dodoex.io/
USDC/USDT -> https://twitter.com/app.dodoex.io/exchange/USDC-USDT
![image](https://user-images.githubusercontent.com/3343358/111936403-899d9980-8b00-11eb-97d7-dc0d11e60781.png)

### Actual Behavior
The correct one should be: https://app.dodoex.io/exchange/TOKEN1-TOKEN2

**Comment by UncleBill** [comment]
Seems it's got fixed already. I don't see any parsing operation for the link (`ticker.trade_url`) either, so it should be the original data.

![image](https://user-images.githubusercontent.com/1141198/114668436-50d59680-9d33-11eb-9117-68a7762d9570.png)

![image](https://user-images.githubusercontent.com/1141198/114669498-8a5ad180-9d34-11eb-822b-2309f6170032.png)


I think it used to wrongly be an absolute url `/app.dodoex.io/exchange/USDT-MASK` without url protocol.
In order to confirm this conjecture, we might inspect the DOM and checkout the `href` attribute if it appears next time.

cc @yisiliu @guanbinrui

**Comment by guanbinrui** [comment]
Maybe it's fixed by upstream. It will close now. Feel free to reopen it if revealed in the future.

**Comment by yisiliu** [comment]
ack. thanks
