### ISSUE TITLE
[Bounty] Integrate dHEDGE in Mask 

### ISSUE THREAD

**Issue by leckylao** [DimensionDev/Maskbook#2678]
### Prize Title
Integrate dHEDGE in Mask plugin

### Prize Bounty
5000 USDC

### Background
On one side there's many KOL/Managers on twitter, and on the other side there's many pools on dHEDGE and we would like to find a way to link it together:
Twit: https://twitter.com/dHedgeOrg/status/1375554472345174016
KOL/Manager: https://twitter.com/PerceptronCap
Pool: https://app.dhedge.org/pool/0x3a4851597f36f459b58e65c55c8f3a8710313fc7
Pool Token: https://etherscan.io/token/0x3a4851597f36f459b58e65c55c8f3a8710313fc7

### Solution
Create a new dHEDGE plugin that similar to the current Gitcoin plugin, which will detect links from https://app.dhedge.org/pool instead of https://gitcoin.co/grants and show the pool information, trade to invest with SUSD and plot the chart using the existing Mask chart plugin to be consistent.  

There would be 3 tabs:
- The first tab would be the basic pool info. such as pool name, managed by, strategy, last active, AUM, return, fees and risk factor. With an invest button align with the current Gitcoin plugin. `Donate` button would be the `Invest` button. Before clicking the invest there's `Enable` button for approving the SUSD token as in reference image. After clicking invest would pops up to invest with SUSD. And there would be a link with `Get SUSD` which jumps to the second tab. 

![image](https://user-images.githubusercontent.com/148800/113661582-bd281880-96e9-11eb-911d-e24b54120a56.png)

![image](https://user-images.githubusercontent.com/148800/113661880-4b9c9a00-96ea-11eb-8672-bd3875c62fdd.png)

![image](https://user-images.githubusercontent.com/148800/113804524-02a81c80-97a2-11eb-8bde-130d1956cd6d.png)

- Second tab would be the Mask trading widget for user to get SUSD

![image](https://user-images.githubusercontent.com/148800/113803786-8fea7180-97a0-11eb-9f58-3f3bf9b64e2a.png)

- Third tab would be the pool chart which uses Mask chart plugin to keep it consistent. 

![image](https://user-images.githubusercontent.com/148800/113662079-b9e15c80-96ea-11eb-9724-6b04942b1c60.png)

## Part 2: Resources
- dHEDGE Docs: https://docs.dhedge.org/
- Maskbook plugins: https://github.com/DimensionDev/Maskbook/tree/master/packages/maskbook/src/plugins

## Part 3: Contact and Support
- dHEDGE Discord: https://discord.gg/BAWTbRA
- MaskBook Discord: https://discord.gg/4SVXvj7

### Submission Requirements
Please include demo to show the integration is working. 

### Winner Announcement Date
Winners will be announced at the conclusion of Open Defi Hackathon

### Judging Criteria
- Have a working demo. 
- Clean code & tech design
- Clear UI, easy to use and generally good user experience

**Comment by septs** [comment]
CC @yisiliu @Tedko

**Comment by yisiliu** [comment]
@leckylao hey Lecky have you funded this issue on Gitcoin? If not, do you need me to do so?

**Comment by leckylao** [comment]
> @leckylao hey Lecky have you funded this issue on Gitcoin? If not, do you need me to do so?

This is still a draft, still waiting for confirmation details for the technical feasibility.

**Comment by Tedko** [comment]
👍🏻👍🏻 @leckylao

**Comment by dtbx** [comment]
Looks like an epic bounty!

**Comment by tzhan28** [comment]
A few glitches

1. Under soultion it says coinbase plugin, should be gitcoin.
2. Maybe specify that the UI should somewhat be in line with the card style in the gitcoin plugin, but there should be multiple tabs with in the card, which is more similar to the uniswap popup. Perhaps one tab being the basic info, one being the chart, and one being the social comments?
3. For the 1 click invest, there should be a place to acquire susd, which our trading plugin can provide. Wonder if it can be done in 1 tx instead of 2 to save gas? I saw on Dhedge website that there is a button to acquire SUSD which links to 1inch.

**Comment by tzhan28** [comment]
A few Glitches

1. Under solution it says Coinbase plugin, should be gitcoin.
2. Maybe specify that the UI should somewhat be in line with the card style in the gitcoin plugin, but there should be multiple tabs with in the card, which is more similar to the uniswap popup. Perhaps one tab being the basic info, one being the chart, and one being the social comments?
3. For the 1 click invest, there should be a place to acquire susd, which our trading plugin can provide. Wonder if it can be done in 1 tx instead of 2 to save gas? I saw on Dhedge website that there is a button to acquire S which links to 1inch.

Should be good to go in no time

**Comment by leckylao** [comment]
> A few glitches
> 
> 1. Under solution it says Coinbase plugin, should be gitcoin.
> 2. Maybe specify that the UI should somewhat be in line with the card style in the gitcoin plugin, but there should be multiple tabs with in the card, which is more similar to the uniswap popup. Perhaps one tab being the basic info, one being the chart, and one being the social comments?
> 3. For the 1 click invest, there should be a place to acquire susd, which our trading plugin can provide. Wonder if it can be done in 1 tx instead of 2 to save gas? I saw on Dhedge website that there is a button to acquire Susd which links to 1inch.
> 
> Should be good to go in no time.

Fixed typo and updated the UI requirements with 3 tabs.

**Comment by septs** [comment]
@leckylao we need a dHEDGE plugin icon in dashboard plugins page.

<img width="1138" alt="CleanShot 2021-06-15 at 14 11 16@2x" src="https://user-images.githubusercontent.com/3842474/122001880-9241fb00-cde3-11eb-8cd6-c2731f163c27.png">

**Comment by leckylao** [comment]
Maybe try this one. 
![image](https://user-images.githubusercontent.com/148800/122002193-c671e780-cdf4-11eb-8410-070ef07aa5bf.png)
