### ISSUE TITLE
[Demand] Customized Qualification Contract

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2798]
## Catalogue

- [ ] UI/UX
- [ ] Mask Core Feature
- [x] Mask Plugin Feature (ITO)
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

**Comment by yisiliu** [comment]
All you need to do is to add a new field in the ITO composition card and **only** accepts a valid qualification contract address. Qualification check could be as simple as checking the ABI and compare if it has `logQualified()` and `ifQualified()` functions and if their signatures match. What do you think?

**Comment by zhouhanseng** [comment]
How to detect it has `logQualified()` and `ifQualified()` functions if the author does not publish source code?

One feasible way is ERC165 must be implemented to qualification contract. We can tell user this requirement and provide the interfaceID both at Front-end and [InitialTwitterOffering/README](https://github.com/DimensionDev/InitialTwitterOffering).

**Comment by zhouhanseng** [comment]
https://github.com/DimensionDev/InitialTwitterOffering/pull/20/commits/5be4a4b384d3b37c4b45163c426b8f4b1f30984b

We ask the user to inherit our abstract contract `IQLF` to their custom qualification contract to ensure things work well, since user also want things work well, and there's no gas consumption through overall process.
