### ISSUE TITLE
Discussion: when to publish the key to Gun?

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#318]
By https://github.com/DimensionDev/Maskbook/pull/317 Maskbook will be able to post the AESKey after the user actually post the post to the network.

As the comment leaved at `publishPostAESKey()`

> TODO: If we can use PostIVIdentifier to avoid this hacking way to publish PostAESKey?

**Comment by neruthes** [comment]
Not sure how related, but I would like to talk about the [payload](https://github.com/DimensionDev/Maskbook/wiki/Payload-of-posts-and-comments) with this chance.

I wrote in #223 that I suggested that every post should have a PostUUID so that identifying a post will not rely on its URI, which does not exist before publishing the post. With PostUUID embedded in the payload, data management might be easier in future combats with possible platform-specific post-identifying problems.

**Comment by Jack-Works** [comment]
We do have a internal representation for that.

A post have two type of identifiers.

1. PostIdentifier(network, postID) for any post they have this id.
2. PostIVIdentifier(network, iv) only posts that created by maskbook have this type of identifier.
