### ISSUE TITLE
Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#36]
Hard to reproduce.
Suspect this bug is related to the outcome of some user changed their identifier.
**Also, sometimes the contacts cached in the browser will lost.**
![Screen Shot 2019-05-21 at 16 21 48](https://user-images.githubusercontent.com/6687437/58079851-8d022a00-7be4-11e9-8132-d1fb443de87d.png)

**Comment by Jack-Works** [comment]
Maybe new database structure can help this.

**Comment by Jack-Works** [comment]
Yes, I find out why. We use `typed-db` before, and it requires a Class and uses it's as the objectStore name. Things run fine in development, but in production mode, because the class is not exported, its name is mangled. For example: `database/AvatarStore` becomes `database/i`, and the toolchain may change the mangled name from `i` to `j` `k` etc. After user upgrades the Maskbook and the mangled name changed, this problem happened.

**Comment by Tedko** [comment]
Just found out the same bug will cause:
 after click on 'Post it!', no encrypted text showed up (or copied in the clipboard)

Let's test the new DB structure to see will this problem still exist and see whether we need to do sth
