### ISSUE TITLE
[Bug] WalletConnect on iOS completely not working

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#3801]
## Bug Info

Try go to dashboard -> wallet -> connect a wallet (imtoken/rainbow etc) through Wallet connect on Eth L1;

-> Not working.

While other walletconnect solution like Zerion is working perfectly.

@wenluomask take a look of these aspects on mobile as well. 
@jk234ert @MainasuK lets do a hotfix and publish a new ver on iOS. Been 2weeks since last one

### How to reproduce?

1.
2.
3.

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by wenluomask** [comment]
Here is what I tried:

1. Use WalletConnect to connect Metamask successfully, but fail to change other wallets since the connect wallet icon on dashboard's wallet page is unresponsive.
2. Use WalletConnect to connect imtoken, unsuccessfully and the prompt is "Please refresh the QR code and try again."

**Comment by UncleBill** [comment]
Should be fixed by #3821

**Comment by wenluomask** [comment]
Checked.
