### ISSUE TITLE
[RFC] Should we call writeProfileOnGun for every person seen on twitter?

### ISSUE THREAD

**Issue by SunriseFox** [DimensionDev/Maskbook#562]
After some investigations, I find that we call `writeProfileOnGun` hundreds of thousands of times when browsing twitter's timeline.  Should we call writeProfileOnGun for every person seen on twitter? Maybe we are spamming our gun network.

**Comment by guanbinrui** [comment]
Here is a snippet from `PostInspector.tsx`

```
if (type.provePost && postId) Services.Identity.writeProfileOnGun(postBy, { provePostId: postId }) {
  /* ommited */
}
```

As literally view `writeProfileOnGun` only runs when `type.provePost` and `postId` both exists. But `type.provePost` is a string array instead of string. Since the condition always yield `true`.

**Comment by guanbinrui** [comment]
Here is a snippet from `PostInspector.tsx`

```typescript
if (type.provePost && postId) Services.Identity.writeProfileOnGun(postBy, { provePostId: postId }) {
  /* ommited */
}
```

As literally view `writeProfileOnGun` only runs when `type.provePost` and `postId` both exists. But `type.provePost` is a string array instead of string. Since the condition always yield `true`.

We can change the condition to `if (type.provePost.length && postId) {}`, in that case will reduce the performance problem.

**Comment by Jack-Works** [comment]
> write every person on gun

that was designed as a feature: when every time someone sees a prove post, write it on the gun. So once the prove post been seen, the correct address will be updated on the gun.
