### ISSUE TITLE
Dashboard Revamp

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#70]
Components:

- Dashboard / Initialization
  - 
- Dashboard / Main
  - Add Persona
    - [PersonaCreation] Modal
      - Procedure:
        - Enter name
        - Get keypair
        - Connect first profile
  - Delete Persona
    - Popup Confirmation
  - Add Profile
    - [ProfileBinding] Modal
      - Procedure:
        - Enter profile URI
        - Get guides to paste public key into profile biography
  - Delete Profile
    - Popup Confirmation
  - Export Persona
  - Import Persona
  - Export Keystore
  - Import Keystore
- Dashboard / Synchronization
  - Add Device
  - Rename Current Device
  - Quit Current Misakanet

**Comment by SunriseFox** [comment]
As we are going to support multiple identities and multiple providers, some changes we may need to apply to our dashboard:

+ Possibly rename current menu item `Setup your account` to `Initialize your Maskbook`, in which we could provide an all-in-one setup for all providers (facebook, twitter, etc.).
+ Add `Identity Management` menu item, allowing user to **add more keystores**, **select default keystore for each provider**, **disable/enable each keystore** (e.g. if enabled, we may try using this keystore to decrypt otherwise not), **retrieve public keys** (create/recreate proof post, #79 ) or completely **remove them**. 

As a user may use more than one identity and thus own multiple keystores, cross-device transfer by a QR code which contains full keystore information seems not quite practical. So maybe a (distributed) bridge server is still needed. #77 we create a secure channel, and sync all / user-selected keystore by this channel with trusted pair.

Before that we also have to decide how the user may identify their identities, or rather, keystores.  A user with multiple keys may get confused when managing them. We may assign a randomly generated English word to each keystore, or let user 'tag' it manually. Any other better solutions? 

##### Summary in this issue

+ New initialization page for more providers
+ New setting page for identity management
+ New approach for tagging identities

**Comment by Tedko** [comment]
<img width="338" alt="Screen Shot 2019-08-22 at 00 39 27" src="https://user-images.githubusercontent.com/6687437/63496061-07597900-c476-11e9-8c11-9be21b496058.png">
<img width="334" alt="Screen Shot 2019-08-22 at 00 39 52" src="https://user-images.githubusercontent.com/6687437/63496064-09bbd300-c476-11e9-8ca1-e43f885d1874.png">


Mentioned in #79

**Comment by neruthes** [comment]
Preview.

<img width="615" alt="Screen Shot 2019-09-09 at 06 34 45" src="https://user-images.githubusercontent.com/2139261/64508099-fe690400-d2cb-11e9-82f4-70251101f517.png">
<img width="730" alt="Screen Shot 2019-09-09 at 06 34 19" src="https://user-images.githubusercontent.com/2139261/64508100-fe690400-d2cb-11e9-9a59-ccd9e0ba30f5.png">

**Comment by SunriseFox** [comment]
In the new dashboard, where should we put the privacy policy, developer options, etc. ?

**Comment by neruthes** [comment]
> In the new dashboard, where should we put the privacy policy, developer options, etc. ?

We may add these links under the last button.

`font-size: 16px; color: #999999; margin-top: 40px;`

![image](https://user-images.githubusercontent.com/2139261/67378323-9b2eea80-f576-11e9-9cdb-024f7e743d64.png)

**Comment by neruthes** [comment]
Seems that this image was neglected.

<img width="874" alt="Screen Shot 2019-10-25 at 10 32 39" src="https://user-images.githubusercontent.com/2139261/67933650-25ea9780-fbbe-11e9-9a30-432cbebfeb9a.png">

We will switch to Figma for Maskbook in future to allow non-Mac reading.

**Comment by neruthes** [comment]
Asset for close button

- Button size 40*40px
- Icon size 24*24px
- Top-right corner
- `box-shadow: 0 1px 4px 0 rgba(0,0,0,0.50);`

[close_24px.svg.zip](https://github.com/DimensionDev/Maskbook/files/3803577/close_24px.svg.zip)

<img width="1440" alt="Screen Shot 2019-11-04 at 10 38 54" src="https://user-images.githubusercontent.com/2139261/68115037-5c425280-feef-11e9-8ab3-b10e4f6dc687.png">

<img width="387" alt="Screen Shot 2019-11-04 at 10 41 16" src="https://user-images.githubusercontent.com/2139261/68115165-aa575600-feef-11e9-8eac-60fc7992fc73.png">

cc @SunriseFox

**Comment by neruthes** [comment]
## Update

We use a  modal header to keep a consistent behavior across different screens. When on mobile where the can be no margin out of the modal, border-radius should be 0px; otherwise, 6px.

- Modal max-width 600px

### Header

- Header 44px height
- box-shadow: rgba(0,0,0,0.15) 0 1px 0
- Title font: 17px medium '-apple-system'
- Close button inner size 24px
- Close button outer size 44px

### Body

- padding: 40px 0 50px
- Content max-width: 500px

<img width="656" alt="Screen Shot 2019-11-04 at 11 16 15" src="https://user-images.githubusercontent.com/2139261/68117200-906c4200-fef4-11e9-8213-eb33a647686b.png">

**Comment by Jack-Works** [comment]
:awsl: it is toooo anti-material design and remind me of antd. I strongly recommend not to do this plz.

**Comment by SunriseFox** [comment]
Followed by #369.
