### ISSUE TITLE
[Discussion] In-GUN data loss

### ISSUE THREAD

**Issue by SunriseFox** [DimensionDev/Maskbook#90]
Gun Server has a by-design flaw that allow any users to retrieve or detach any data in it. That is, if one looks into our code or tries to capture the extension's traffic, they can easily download the whole database or erase(detach) anything in the database. And that is just how a distributed database server works. 

However, some data in the GUN, i.e., the data in the `posts` node, are critical for our extension to function. It should never be removed (or rather, detached) by anyone. GUN doesn't have such a method to deal with this situation (even if it does, possibly not useful at all). 

So I request a discussion about how to work it out.

**Comment by neruthes** [comment]
## Surgical-Strike Denial-of-Communication

As I understand GUN, it has a recursive key-value pair structure like JSON. If that is not the fact, please feel free to tell me more details. With this assumption, it is easy to hash everything and attackers will have no idea which nodes belong to Maskbook without effective surveillance on machines running Maskbook.

For example, the recipient-specific ECDH-encrypted AES key can be stored at location `SHA512(DH(Alice.pri, Bob.pub) + "---MaskbookEnvoy---" + Date)` where `Date` is in `YYYYMMDD` format.

With Diffie-Hellman, Alice and Bob can calculate a shared secret which works a seed to find the location where this payload is stored. If we implement this, it will be impossible for an attacker to find the exact location of the payload.

For scenarios where Diffie-Hellman secret exchange is impossible, like which involve publicity, the situation differs. Since no private knowledge is held by the appropriate recipients, an attacker will have all the information necessary. For this, what we ultimately require is a server-side mechanism which ensures signed data immutability with trustable expiry statement. It would be like that there is an access-control-protected node where only the owner, which is identified as a keypair, is allowed to operate its sub nodes through digital signature, and this access-control system must be universally implemented and acknowledge by all GUN peers. I assume that this feature will remain unimplemented for a moderately long period of time. On this matter, we will have to consult @amark to figure out whether this may be scheduled in near-future development plan.

## Massive Overwrite

Similarly, this may also require the feature mentioned above. If access-control remains unimplemented, I suspect that it will be impossible to prevent a massive overwrite from happening.


--------

I look forward to seeing more ideas on this affair. Thanks everyone.

**Comment by amark** [comment]
@SunriseFox @neruthes @yisiliu @Tedko 

GUN's module SEA does exactly this.

Data saved to a User graph with SEA cannot be modified, written, altered, deleted, or tampered by anyone other than the author.

The largest scale we ran the current version at has been with 8K simultaneously connected people, on 1 free Heroku instance, for HackerNoon.

SEA is optional tho, so make sure it is installed & configured. If you need help with that, let me know.

**Comment by amark** [comment]
ECDH @neruthes ,

```
var alice = await SEA.pair(); // alice keypair
var bob = await SEA.pair(); // bob keypair

var sec = await SEA.secret(bob.epub, alice); // Alice derives shared secret
var enc = await SEA.encrypt('hi bob!', sec); // encrypt message

var sec = await SEA.secret(alice.epub, bob); // Bob derives shared secret
await SEA.decrypt(enc, sec); // Bob decrypts message
```

What I've done is save messages like `user.get('messages').get('to').get(bob.pub).set(enc);` (if you want to mask who talks to who, you could replace `bob.pub` with a `await SEA.work(bob.pub+sec, null, null, {name: "SHA-256"})` this way both users can deterministically hash a combined secret they know that others don't, but nobody observing can reverse who it was to), then all Bob has to do is lookup messages for him on Alice's graph `gun.user(alicePubKey).get('messages').get('to').get(bob.pub).map().on(cb)`! :)

Again, since these are saved to the user graph, nobody can alter or tamper them with SEA.

Pretty much all AXE peers will be running SEA to enforce security.

**Comment by Tedko** [comment]
@SunriseFox @Jack-Works  Let's try out GUN's SEA.
