### ISSUE TITLE
[Bug] Camera bug

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#970]
# Bug Report
<img width="471" alt="Screen Shot 2020-04-11 at 21 22 04" src="https://user-images.githubusercontent.com/6687437/79047302-5e4fd080-7c48-11ea-8631-8a8e0ff5ebdd.png">
<img width="296" alt="Screen Shot 2020-04-11 at 21 22 29" src="https://user-images.githubusercontent.com/6687437/79047304-5f80fd80-7c48-11ea-97ec-991fbdaa622d.png">

Should able to:
1. fix macbook related bugs
2. select camera on Laptop such as surface(?)

### System

- OS:
- OS Version:

### Browser

- Browser:
- Browser Version:

### Maskbook

- Maskbook Version:
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

### Expected Behavior

/* Write the expected behavior here. */

### Actual Behavior

/* Write the actual behavior here. */

### How To Reproduce

/* Specify how it may be produced here. */

**Comment by septs** [comment]
Use cases:
1. Camera unavailable (Hint message?)
2. One Camera available
3. Multiple Camera available (Multi-cam switching?)
4. Permission denied (re-request permission?)

CC @neruthes 
CC @OiCkilL need to redesign, **import via QR scanning**

**Comment by neruthes** [comment]
## Features

Feature | Stage 1 | Stage 2
--- | --- | ---
Unavailability Hint | ✓ | ✓
Switch Camera |  | ✓
Permission Management |  | ✓

## Stage 1

### Baseline

There should be 1 camera available, or multiple cameras available. If Maskbook finds multiple cameras available, platform-specific optimal camera selection strategies should be used.

### Unavailability Hint

There should be a line of notice text in the camera image area when no camera input. This includes hardware absence and permission denial.

Language | Text
--- | ---
en | Cannot find a camera.
zh | 未能找到攝像頭。

## Stage 2

### Switch Camera

If multiple cameras are available, Maskbook will display a camera selection dropdown menu above the preview area.

### Permission Management

If Maskbook detects that the absence of camera signal input is caused by permission instead of hardware, by judging whether the current platform supports re-requesting the permission, Maskbook will display an appropriate message here.

// TODO

**Comment by OiCkilL** [comment]
> Use cases:
> 
> 1. Camera unavailable (Hint message?)
> 2. One Camera available
> 3. Multiple Camera available (Multi-cam switching?)
> 4. Permission denied (re-request permission?)
> 
> CC @neruthes
> CC @OiCkilL need to redesign, **import via QR scanning**

1. We may add a "browse" button first? Most PC did not have any camera.

**Comment by septs** [comment]
> > Use cases:
> > 
> > 1. Camera unavailable (Hint message?)
> > 2. One Camera available
> > 3. Multiple Camera available (Multi-cam switching?)
> > 4. Permission denied (re-request permission?)
> > 
> > CC @neruthes
> > CC @OiCkilL need to redesign, **import via QR scanning**
> 
> 1. We may add a "browse" button first? Most PC did not have any camera.

External file need to deal with more unavailable issues
1. Broken file
2. Unrecognized picture
3. Multiple QRCode in One picture issue
4. Timeout logic

**Comment by septs** [comment]
@neruthes @Tedko The issue level is P2 or P3?

**Comment by Tedko** [comment]
Baseline = p2 (can not find camera etc)
Others p3

**Comment by OiCkilL** [comment]
<img width="1033" alt="截屏2020-04-14下午1 47 35" src="https://user-images.githubusercontent.com/613988/79190297-89a80a80-7e56-11ea-8cf3-07e3b947f673.png">
One or multiple camera switch use drop-down menu.
Disable the drop-down menu and scan button when camera unavailable.

**Comment by Tedko** [comment]
<img width="130" alt="Screen Shot 2020-07-29 at 12 30 58" src="https://user-images.githubusercontent.com/6687437/88757000-9b0feb00-d197-11ea-9478-06d185bbc990.png">
orz

Anyway this is fixed (tested on chrome ver). will close this issue
